<%@ Page Title="TaxGenieOnline" Language="C#" MasterPageFile="~/TaxGenie.master" AutoEventWireup="true" CodeBehind="editnotifications.aspx.cs" Inherits="TaxGenieOnline.admin.editnotifications" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit.HTMLEditor"
    TagPrefix="cc1" %>
<%@ Register Assembly="TaxGenieOnline" Namespace="TaxGenieOnline.Controls" TagPrefix="asp" %>
<asp:Content ID="Content1" ContentPlaceHolderID="cph_left" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cph_main" runat="server">
  <div class="cl2 fleft">
        <div class="contentbox">
           <%-- <img src="../images/middle_box_top.png" width="726" height="4" alt="" />--%>
            <div class="contentboxmiddle1 shdw shd" style="min-height: 300px;">
               <table style="width: 100%; margin-top: 5px;">
                    <tr>
                        <td style="width: 20%; text-align: right">
                            <asp:Label ID="lblCategory" runat="server" Text="Category" CssClass="nlsN"></asp:Label>
                        </td>
                        <td style="width: 25%; text-align: left">
                            <asp:DropDownList ID="ddlcatagory" runat="server" CssClass="nls" AutoPostBack="true"
                                OnSelectedIndexChanged="ddlcatagory_SelectedIndexChanged">
                                <asp:ListItem>select one</asp:ListItem>
                                <asp:ListItem>Central Excise</asp:ListItem>
                                <asp:ListItem>Customs</asp:ListItem>
                                <asp:ListItem>Service Tax</asp:ListItem>
                                <asp:ListItem>Income Tax</asp:ListItem>
                                <asp:ListItem>DGFT</asp:ListItem>
                                <asp:ListItem>Library</asp:ListItem>
                                <asp:ListItem>Services</asp:ListItem>
                            </asp:DropDownList>
                            <asp:RequiredFieldValidator ID="rfvddlcat" runat="server" ControlToValidate="ddlcatagory"
                                InitialValue="select one" ErrorMessage="*" ValidationGroup="ddlcat"></asp:RequiredFieldValidator>
                        </td>
                        <td style="width: 20%; text-align: right">
                            <asp:Label ID="lblSubCategory" runat="server" Text="SubCategory" CssClass="nlsN"></asp:Label>
                        </td>
                        <td style="width: 35%; text-align: left">
                            <asp:DropDownList ID="ddlsubcategory" runat="server" CssClass="nls" Width="150" OnSelectedIndexChanged="ddlsubcategory_SelectedIndexChanged"
                                AutoPostBack="true">
                            </asp:DropDownList>
                        </td>
                    </tr>
                </table>
                <br />
                <asp:GridView ID="editGrid" Width="100%" runat="server" 
                    AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
                    onrowediting="editGrid_RowEditing" onrowdeleting="editGrid_RowDeleting" 
                    onrowdatabound="editGrid_RowDataBound">
                     <HeaderStyle BackColor="#D9D9D9" ForeColor="#002700" Height="25px" CssClass="nlsHl" />
                     <AlternatingRowStyle BackColor="#d0d0d0"></AlternatingRowStyle>
                     <RowStyle CssClass="eg" />
                </asp:GridView>
                <asp:PagerControl ID="UPager" runat="server" OnCommand="UPager_Command" PageSize="10" Visible="false"
                    Font-Bold="True" GenerateSmartShortCuts="True" GeneratePagerInfoSection="True" GenerateHiddenHyperlinks="True" GenerateFirstLastSection="True" GenerateToolTips="True" />
                <asp:GridView ID="gvCaseLaws" Width="100%" runat="server"  Visible="false"
                    AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
                    onrowediting="gvCaseLaws_RowEditing" 
                    onrowdeleting="gvCaseLaws_RowDeleting" onrowdatabound="gvCaseLaws_RowDataBound">
                     <HeaderStyle BackColor="#D9D9D9" ForeColor="#002700" Height="25px" CssClass="nlsHl" />
                     <AlternatingRowStyle BackColor="#d0d0d0"></AlternatingRowStyle>
                     <RowStyle CssClass="eg" />
                </asp:GridView>
                <br />
            </div>
           <%-- <img src="../images/middle_box_bottom.png" width="724" height="6" alt="" />--%>
        </div>
    </div>
</asp:Content>